### ISSUE TITLE
I was wondering how it would be possible to use melody generation on a specific song, as you demonstrated on medium

### ISSUE THREAD

**Issue by Aidan-WW** [Elvenson/midiMe#21]
Hi there!

Apologies for asking a question about an old project, I hope you're still active & haven't forgotten about this project - I very much like it!

Yea I have a simple question, when on the sample section; loading the model for melody generation and then outputting generated MIDIs. How is this done for a target song, as your medium post shows SmallMusicVAE reproducing Fur Elise for example?

This is a simple question, and I'm hoping that I'm missing something obvious - I've spent a very long time on this and haven't been able to figure it out myself, unfortunately.  

Thanks & all the best!

**Comment by Elvenson** [comment]
Hi there,
Thanks for using my project! As for your question, I have added sample data in the `data` folder. So you can checkout the latest master branch to try. You can read the `Example` section in `README.md` for more information.

**Comment by Aidan-WW** [comment]
Hi there,
Thanks very much, I thought it was something like that - very well explained!
